

export default function getOrgs()  {
    const organisms = [
        {name: "Black Oyster Catcher", scientific:"Haemotopus bachmani", type: "bird", web:'Black_Oyster_Catcher',
                                range:"Pacific Coast shorelinnes from Northern Alaska to Baja",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/251509444/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/119966270/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/185780288/medium.jpg"],
                                features: "Reddish bill, yellow eyes, pink legs, black head and neck, chocolate brown body",
                                fact0: "They remain paired up all year round!", fact1: "They have high, rising whistled calls!"},
        {name:"California Brown Pelican", scientific:"Pelecanus occidentalis",type: "bird",web:'California_Brown_Pelican',
                                range:"Vancouver, Canada to Central Mexico",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/315799364/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/316093565/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/331469621/medium.jpg"],
                                features: "Up to 4ft tall, can have 6.5ft wingspan, glides on top of ocean, brown body."+
                                            "Adults have a white neck and a yellow head",
                                fact0: "They were classified as federally endangered in 1970 and as endangered by the state of "+
                                    "California in 1971, but were delisted as a federally listed species in 2009.",
                                fact1:"The only breeding colonies of California brown pelicans in the western United States "+
                                "are within Channel Islands National Park on West Anacapa and Santa Barbara islands."},
        {name: "California Least Tern", scientific:"Sternula antillarum browni", type: "bird",web:'California_Least_Tran',
                                range:"California Coast",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/53562544/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/8824528/medium.jpg"],
                                features: "Forked tail, black-capped head and black-tipped wings, yellow bill and legs.",
                                fact0: "These birds are protected under the multi-nation Migratory Bird Treaty", 
                                fact1: "They fly over water in a hunchbacked position with the bill pointing slightly downward."},
        {name: "Snowy Egret", scientific:"Egretta thula", type: "bird",web:'Snowy_Egret',
                                features: "Yellow feet with black legs, black bill with yellow skin at the base, long and slender neck.",
                                range:"Year-round off Southern California, coastal and wetlands",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/2969404/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/281900093/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/40440032/medium.jpg"],
                                fact0: "Male and female Snowy Egrets take turns incubating their eggs.", 
                                fact1: "Adults develop long, wispy feathers on their backs, necks, and heads during mating season."},
        {name: "Western Snowy Plover", scientific:"Charadrius alexandrinus nivosus", type: "bird",web:'Western_Snowy_Plover',
                                range:"Pacific coast, going 80 km inland",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/143452313/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/174495992/medium.jpeg"],
                                features: "Small, with a dark bill and legs, large eyes, sand colored with a dark strip behind the eye.",
                                fact0: "Sadly listed as threatened under the US Endangered Species Act.", 
                                fact1: "At the Bolsa Chica Ecological Reserve in they have been observed in shallow water doing a little “dance” in which they shake and tap a foot to cause a vibration that scares up burrowed prey."},
        {name: "Brandt’s Cormorant", scientific:"Urile penicillatus", type: "bird",web:'Brandts_Cormorant',
                                range:"Year-round off the California coast",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/229641625/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/341331916/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/227828069/medium.jpeg"],
                                features: "adults in breeding plumage are mostly black, with blue eyes, vivid blue gular pouch, and whiskery white feathers on the head, neck, and shoulders. Nonbreeding adults are uniformly black. Juveniles are brownish overall.",
                                fact0: "The largest cormorant on the Pacific Coast", 
                                fact1: "They are deep divers, diving up to 200 ft for food!"},
        {name: "Pelagic Cormorant", scientific:"Urile pelagicus", type: "bird",web:'Pelagic_Cormorant',
                                range:"Year-round off the California coast",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/111919265/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/184139627/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/319271919/medium.jpeg"],
                                features: "long, thin neck, a long tail, and a narrow, small head. Breeding adults are blackish, with green or purple gloss. Juveniles are uniformly dark brown.",
                                fact0: "Rarely seen more than a few miles from land.", 
                                fact1: "They can hold their breath for 2 minutes and dive as deep as 138 feet to catch fish."},
        {name: "Pigeon Guillemot", scientific:"Cepphus columba", type: "bird",web:'Pigeon Guillemot',
                                range:"Year-round off the California coast",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/119965994/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/280473004/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/185771742/medium.jpeg"],
                                features: "red feet, dark brown plumage with a white patch on their wings.",
                                fact0: "They stay fairly close to shore where they forage along the seafloor for small fish, worms, and crustaceans.", 
                                fact1: "They nest on cliffs"},
        {name: "Surfbird", scientific:"Calidris virgata", type: "bird",web:'Surfbird',
                                range:"Rocky Pacific shorelines during non-breeding seasons",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/57306006/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/98670371/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/13020846/medium.jpg"],
                                features: "short yellow legs, white and black bill, speckled belly.",
                                fact0: "Their winter range is among the longest and narrowest of any North American breeding bird (from Alaska to the Strait of Magellan, Chile, nearly 11,000 miles.", 
                                fact1: ""},
        {name: "Sooty Shearwater", scientific:"Ardenna grisea", type: "bird",web:'Sooty_Shearwater',
                                range:"pelagic, can be found off the pacific coast during non-breeding seasons.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/277761261/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/106244851/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/202994644/medium.jpg"],
                                features: "Dark brown plumage with silver flashes in the underwing, hooked bill.",
                                fact0: "Under optimal conditions, migrating Sooty Shearwaters may cover more than 1,000 miles in a single day.", 
                                fact1: "They can dive as deep as 220 feet below the surface."},
        {name: "Cassin's Auklet", scientific:"Ptychoramphus aleuticus", type: "bird",web:'Cassins_Auklet',
                                range:"found year-round off the Pacific coast",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/344308675/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/186091407/medium.jpeg"],
                                features: "small, round, dark grey plumage, grey eye with white crescent above it, pale spot at base of bill.",
                                fact0: "Spend most of their lives at sea and only return to their nesting burrows under cover of darkness.", 
                                fact1: ""},
        {name: "Black Turnstone", scientific:"Arenaria melanocephala", type: "bird",web:'Black_Turnstone',
                                range:"found of the Pacific coast during non-breeding seasons.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/59811098/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/189124847/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/174204334/medium.jpeg"],
                                features: "Dark brown with a white belly, slightly upturned bill, breeding adults have white spot by base of bill.",
                                fact0: "They flip over rocks, shells, and seaweed to grab flies and fish eggs or hammer open shellfish", 
                                fact1: "On the breeding grounds, Black Turnstonesare extremely aggressive."},
        {name: "California Sea Lion", scientific:"Zalophus californianus", type: "mammal",web:'California_Sea_Lion',
                                range:"southeast Alaska to the Pacific coast of central Mexico",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/202276183/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/109345932/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/47197291/medium.jpg"],
                                features: "brown in color with whiskers, external ear flaps, rotating flippers. Mature males are larger with a large sagittal crest. Their vocalization is a bark.",
                                fact0: "Protected through the Marine Mammal Protection Act", 
                                fact1: "A rafting sea lion holds its flippers above the water for a long time, motionless, to rest and regulate its body temperature."},
        {name: "Harbor Seal", scientific:"Phoca vitulina", type: "mammal",web:'Harbor_Seal',
                                range:"Found all along the Pacific coast.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/305341499/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/75773642/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/141603362/medium.jpg"],
                                features: "short flippers, no external ear flap, can be up to 6 feet in length..",
                                fact0: "They haul out (rest) on rocks, reefs, beaches, and drifting glacial ice when they are not traveling and/or foraging at sea to regulate their body temperature.", 
                                fact1: "Their pelvic bones are fused, preventing them from moving their hind flippers under their pelvis to walk on land like sea lions."},
        {name: "Bottlenose Dolphin", scientific:"Tursiops truncatus", type: "mammal",web:'Bottlenose_Dolphin',
                                range:"Found in temperate and tropical waters around the world.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/185330161/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/65995185/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/57008469/medium.jpeg"],
                                features: "gray in color with a short rostrum. Can get up to 12 feet in length. Nearshore bottlenose are shorter and lighter in color than offshore bottlenose.",
                                fact0: "Can live at least 40 years and is protected through the Marine Mammal Protection Act", 
                                fact1: "Use echolocation to communicate and find food."},
        {name: "Bat Star", scientific:"Patiria miniata", type: "invertebrate",web:'Bat_Star',
                                range:"Alaska to Baja in tidepools and kelp forests.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/13265113/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/356407949/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/348036851/medium.jpg"],
                                features: "can be mottled or solid in color (orange, red, purple, brown), has webbing between its 4-9 arms, can be 20 cm across.",
                                fact0: "Scavenges on a variety of plants and animals, dead or alive.", 
                                fact1: "Covered in flat, crescent-shaped plates called ossicles."},
        {name: "Brittle Star", scientific:"Ophiuroidea", type: "invertebrate",web:'Brittle_Star',
                                range:"Can be found from the poles to the tropics, in tidepools to the deep-sea.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/249439950/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/300560116/medium.jpeg"],
                                features: "Generally have 5 slender and spiny arms connected to a radial disk.",
                                fact0: "Can regrow arms, usually to escape predation.", 
                                fact1: "There are over 2,000 species of brittle stars."},
        {name: "Knobby Sea Star", scientific:"Pisaster giganteus", type: "invertebrate",web:'Knobby_Sea_Star',
                                range:"British Columbia to Mexico in intertidal zones.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/31109113/medium.jpeg","https://inaturalist-open-data.s3.amazonaws.com/photos/48591920/medium.jpeg"],
                                features: "brown and covered in short white spines surrounded by a blue circle. Can get up to 46 cm.",
                                fact0: "They can regenerate their arms!", 
                                fact1: "Sometimes called the “jeweled star”"},         
        {name: "Devil Weed", scientific:"Sargassum horneri", type: "invasive",web:'Devil_Weed',
                                range:"invasive in Baja California, Mexico, southern California, and the California Channel Islands. Native to warm seas in Japan and Korea.",
                                image:["https://static.inaturalist.org/photos/1421979/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/3101148/medium.JPG","https://inaturalist-open-data.s3.amazonaws.com/photos/239425788/medium.jpg"],
                                features: "Small, fern-like leaf blades on wiry stems with many small air bladders. Forms dense groves, can get up to 15 ft long.",
                                fact0: "First reported in California in 2003", 
                                fact1: "Capable of self-fertilization, so it spreads quickly!"},
        {name: "Japanese Wireweed", scientific:"Sargassum muticum", type: "invasive",web:'Japanese_Wireweed',
                                range:"Invasive from British Columbia to Baja. Native in Japan and the Mediterranean Sea.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/11901519/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/161038914/medium.jpg"],
                                features: "A large, yellowish-brown or olive-brown seaweed with small spherical float bladders, can get up to 10 m long.",
                                fact0: "High growth rate (until 10 cm per day during spring). Helped by its efficient dispersion thanks to its floats", 
                                fact1: "Shades light from other plants, outcompeting them."},
        {name: "Wakame", scientific:"Undaria pinnatifida", type: "invasive",web:'Wakame',
                                range:"Invasive in California. Native to Japan.",
                                image:["https://inaturalist-open-data.s3.amazonaws.com/photos/180857433/medium.jpg","https://inaturalist-open-data.s3.amazonaws.com/photos/113232717/medium.jpg"],
                                features: "Large brown kelp, can get up to 3 m. Also edible!",
                                fact0: "It was first recorded in several estuaries in California in 2000.", 
                                fact1: "It can colonize estuaries rapidly if native algae are not present. Occurs in high densities only in recently disturbed areas."}
    ]
    return organisms
}